### ISSUE TITLE
-1301 error code

### ISSUE THREAD

**Issue by RyanWoodruff** [fishbigger/TapoP100#11]
I have been experiencing a -1301 error code (which isn't in the known list) when doing pretty much anything with my tapo L530.

Failure seems sporadic as it happens randomly.

**Comment by arrival-spring** [comment]
I think it's that code that I've been seeing a few times too. It seems to happen after doing lots of requests, possibly in quick succession, and doing the handshake and login again fixes it.
I've put commands to the bulb into a try, except, where the except logs in again.

**Comment by fishbigger** [comment]
Someone else seems to think that -1301 is request timeout so trying to login / do anything too quickly will cause it too throw.
