### ISSUE TITLE
can i turn off and on my bulb L530 with this code?

### ISSUE THREAD

**Issue by Blesivec** [fishbigger/TapoP100#111]
Hello, I am trying to have python code that can turn on and off my bulb L530. I tried: l530.setBrightness(0) but it gave me error: KeyError: '-1008'

**Comment by Edwin-LAC** [comment]
Hello Blesivec, I think this is what you are looking for:

l530.turnOff() #turn bulb off

l530.turnOn() #turn bulb on

**Comment by Blesivec** [comment]
Thanks a lot man, i am dumb i didnt see it
