### ISSUE TITLE
P100 after firmware update to 1.5.5 PyP100 not working anymore

### ISSUE THREAD

**Issue by unterrei** [fishbigger/TapoP100#132]
After a firmware update to 1.5.5 when switching via PyP100 .py an error message is generated in function handshake()
ERROR: "PyP100.py, line 129, in handshake  encryptedKey = r.json()["result"]["key"]

Another P100 with firmware 1.4.9 is working Ok

**Comment by OreoOba** [comment]
Solved
Check https://github.com/almottier/TapoP100

**Comment by Alfredsche** [comment]
It is still not working with P110. `pip install git+https://github.com/almottier/TapoP100.git@main` updated, but login problem still persits. Firmware 1.3.0 Build 230905 Rel. 152200
