### ISSUE TITLE
Hanksharke issue : KeyError: 'result'

### ISSUE THREAD

**Issue by Number-313** [fishbigger/TapoP100#140]
Hello,
I'm having an issue using PyP100

from PyP100 import PyP100
p100 = PyP100.P100("192.168.X.X, "myemail@email.com", "MyPaSsWoRd!")
p100.handshake()
p100.login()
p100.turnOffWithDelay(45)

here's what I get when I execute the script :

root@raspberrypi:/usr/local/bin# shutdown_with_tapo.sh
Traceback (most recent call last):
  File "/usr/local/bin/scripts/tapo_off.py", line 6, in <module>
    p100.handshake()
  File "/usr/local/lib/python3.9/dist-packages/PyP100/PyP100.py", line 129, in handshake
    encryptedKey = r.json()["result"]["key"]
KeyError: 'result'

**Comment by Number-313** [comment]
Alright, with a simple reinstall I could fix my issue :

`pip uninstall pyp100 && pip install git+https://github.com/almottier/TapoP100.git@main`

**Comment by Toug19** [comment]
I got the same issue and I think this is not a normal behaviour. There might some differences between the release version under pip repositories and this one
