### ISSUE TITLE
[QUESTION] Documented communication flow

### ISSUE THREAD

**Issue by robertcasanova** [fishbigger/TapoP100#16]
Hi @fishbigger thx for this project, I started to port it to Node/TS. Is there any reference to the complete flow of communication with the Tapo server?  (handshaking, keys to be passed, etc etc)

Do you reverse engineer it from scratch or there's some documentation available? Thx a lot!

**Comment by fishbigger** [comment]
There is no official documentation but [K4CZP3R](https://github.com/K4CZP3R) documented the work done on the [home assistant forums](https://community.home-assistant.io/t/tp-link-tapo-p100/147792) into the communication protocol of the plug.
