### ISSUE TITLE
How to make the plug to be ON by default?

### ISSUE THREAD

**Issue by maxeq** [fishbigger/TapoP100#18]
Do you know by any chance how to make the plug to be ON after its powered up by default? I want to make the plug to be switched ON by default, because it goes OFF after power outage.

There is huge interest in this feature: community.tp-link.com/en/home/forum/topic/215412 but seems developers cannot do anything about it. Can you code this feature?

**Comment by maxeq** [comment]
My problem is that after a power outage, the p100 does not remember thep revious state and is always turned off.

How do I changeit ?  Is there any setting for a power outage?

**Comment by fishbigger** [comment]
Sadly this is something that has to be implemented on the plug. And as this code purely talks to the plug over its api there is no way to add this feature.
