### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by mduf** [fishbigger/TapoP100#19]
Hello, I've try to install the projet on a Raspberry 3B+ with Raspbian 10.9 (kernel: 5.10.42-v7+)
Here you find screenshot with the problem:
![image](https://user-images.githubusercontent.com/24375654/123147635-92836b80-d45f-11eb-8267-c43c2e8a5256.png)

**Comment by tlkfc8** [comment]
same here :(
OS: Windows Server 2016
Python version: 3.4.4
![image](https://user-images.githubusercontent.com/87097256/124828163-7cba8e00-dfa9-11eb-8cc2-e5563e6ea3e6.png)
