### ISSUE TITLE
Requests post has no timeout

### ISSUE THREAD

**Issue by wlp7s0** [fishbigger/TapoP100#24]
Hello,
I don't have enough experience with python programming, but I'm using HASS via not very reliable connection. Hopefully will fix soon. But, I've noticed that after HASS server restarts, my bulb become unavailable after some time. 
`WARNING (MainThread) [homeassistant.components.light] Updating tapo_p100_control light took longer than the scheduled update interval 0:00:30`
Using tcpdump,  I've noticed that there is no traffic going to the IP address of the bulb.
Initializing HASS restart - drops python error

> homeassistant    | 2021-08-19 16:56:35 WARNING (MainThread) [homeassistant.util.executor] Thread[SyncWorker_3] is sti
ll running at shutdown: File "/usr/local/lib/python3.9/threading.py", line 930, in _bootstrap                        
homeassistant    |     self._bootstrap_inner()                                                                       
homeassistant    |   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner                     
homeassistant    |     self.run()                                                                                    homeassistant    |   File "/usr/local/lib/python3.9/threading.py", line 910, in run                                  
homeassistant    |     self._target(*self._args, **self._kwargs)                                                     
homeassistant    |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker               
homeassistant    |     work_item.run()                                                                               
homeassistant    |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run                   
homeassistant    |     result = self.fn(*self.args, **self.kwargs)                                                   
homeassistant    |   File "/config/custom_components/tapo_p100_control/light.py", line 191, in update                
homeassistant    |     def update(self):                                                                             homeassistant    |   File "/usr/local/lib/python3.9/site-packages/PyP100/PyP100.py", line 114, in handshake          homeassistant    |     r = requests.post(URL, json=Payload)                                                          
homeassistant    |   File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 119, in post                homeassistant    |     return request('post', url, data=data, json=json, **kwargs)                                   homeassistant    |   File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request              
homeassistant    |     return session.request(method=method, url=url, **kwargs)                                      homeassistant    |   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request        
homeassistant    |     resp = self.send(prep, **send_kwargs)                                                         homeassistant    |   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send           
homeassistant    |     r = adapter.send(request, **kwargs)                                                           homeassistant    |   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send           
homeassistant    |     resp = conn.urlopen(                                                                          homeassistant    |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen   
homeassistant    |     httplib_response = self._make_request(                                                        homeassistant    |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_requ
est                                                       
homeassistant    |     httplib_response = conn.getresponse()                                                         homeassistant    |   File "/usr/local/lib/python3.9/http/client.py", line 1349, in getresponse                       
homeassistant    |     response.begin()                                                                              
homeassistant    |   File "/usr/local/lib/python3.9/http/client.py", line 316, in begin                              
homeassistant    |     version, status, reason = self._read_status()                                                 
homeassistant    |   File "/usr/local/lib/python3.9/http/client.py", line 277, in _read_status                       
homeassistant    |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
homeassistant    |   File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
homeassistant    |     return self._sock.recv_into(b)

so.. my logical conclusion was that some kind of process just doesn't die. 
I did open a source code and found 
`r = requests.post(URL, json=SecurePassthroughPayload, headers=headers)`

First link in google showed me 
[https://docs.python-requests.org/en/master/user/quickstart/#timeouts](url)

> If no timeout is specified explicitly, requests do not time out.

I've modified the script and testing locally. Hopefully it will fix my issue.
Thanks

**Comment by mrx23dot** [comment]
current code has timeout
