### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by Triyono123** [fishbigger/TapoP100#31]
Is there any way we could set timer on or off to the device?

**Comment by krasnyd** [comment]
https://gitlab.com/Naqwada/TapoPlug-Rest-API
I found this library that can turn the device ON and OFF after the certain delay (via a function plugOnCountdown and plugOffCountdown).
If I will have time, I will try to implement it in this library and send a pull request.

**Comment by fishbigger** [comment]
Fixed in #43
