### ISSUE TITLE
Know state of the tapo

### ISSUE THREAD

**Issue by JBelmontte** [fishbigger/TapoP100#32]
Hi, can i know if the tapo is on/off? 
I wan to execute turnOff() if the tapo was on and turnOn() if the tapo was off. 
Thanks.

**Comment by kurattila** [comment]
Hi,
simply doing `p100.getDeviceInfo()` will return a pretty descriptive JSON,
which will contain either `'device_on': True` or `'device_on': False`.
This will tell you if Tapo is currently on or off.
