### ISSUE TITLE
Control from external network 

### ISSUE THREAD

**Issue by arnold427** [fishbigger/TapoP100#33]
Hi,

I have my Tapo in a remote location and I want to control them from my home, is that possible?

**Comment by fishbigger** [comment]
Unfortunately the only api that has been reverse engineered for the plugs is the local one so there is no way currently to use this outside of the local network.

**Comment by Raamyy** [comment]
I think you can build something like a proxy server.

Build a normal application that runs on a local machine, and expose it's endpoints to a public domain tunnel.

I didn't try it, but it's just an idea

**Comment by warren-ru** [comment]
Look like some Node.js project doesn't need local IP
https://github.com/dickydoouk/tp-link-tapo-connect

**Comment by warren-ru** [comment]
Most of the routers gives the ability to map some external port to their local devices. I.e., you can map the 8000 port for external IP to the 500 port for a some local device.
@fishbigger could you add optional port parameter, so that we could use one external IP for many local devices in combination with their port numbers?

**Comment by fishbigger** [comment]
I'm not quite sure what you mean by having an optional port parameter. The plugs will only respond on a specific port and my code can't change that. Could you not map different external ports to many different ips with the same port?

**Comment by warren-ru** [comment]
There's no need for a new parameter. I've added it later.
It works fine like
`p100 = PyP100.P100("93.56.x.x:8000", "email@gmail.com", "Password123")`

I map 8000 on my router to local plug's ip and now can control it remotely.

**Comment by arnold427** [comment]
> There's no need for a new parameter. I've added it later.
> 
> It works fine like
> 
> `p100 = PyP100.P100("93.56.x.x:8000", "email@gmail.com", "Password123")`
> 
> 
> 
> I map 8000 on my router to local plug's ip and now can control it remotely.

How do you map it on your router?

**Comment by warren-ru** [comment]
@arnold427 depends on the exact router model

**Comment by olalonde** [comment]
> Unfortunately the only api that has been reverse engineered for the plugs is the local one so there is no way currently to use this outside of the local network.

I'd like to help with this.. Any tips to get started? It feels weird that some APIs were successfully reverse engineered but others not.

**Comment by fishbigger** [comment]
Hi,
The original reverse engineering of the plugs was done by K4CZP3R on his blog ([Reverse engineering tp-link Tapo](https://kacperserewis.net/blog/post/reverse-engineering-tp-link-tapo)https://kacperserewis.net/blog/post/reverse-engineering-tp-link-tapo)) and I believe that that was done by decompiling the android app and finding the api requests in there. This is probably a good start for looking for external control. Good Luck!
