### ISSUE TITLE
P100.getDeviceName() Exception "the JSON object must be str, bytes or bytearray, not dict"

### ISSUE THREAD

**Issue by realzoulou** [fishbigger/TapoP100#41]
Calling P100.getDeviceName() always results in Exception "the JSON object must be str, bytes or bytearray, not dict"

> 
> 2022-01-09 18:55:20 ERROR (MainThread) [custom_components.tplink_tapo_cloud.config_flow] Unexpected exception
> Traceback (most recent call last):
---cut---
>   File "/srv/homeassistant/lib/python3.9/site-packages/PyP100/PyP100.py", line 356, in getDeviceName
>     data = json.loads(data)
>   File "/usr/lib/python3.9/json/__init__.py", line 339, in loads
>     raise TypeError(f'the JSON object must be str, bytes or bytearray, '
> TypeError: the JSON object must be str, bytes or bytearray, not dict

Introduced with PR https://github.com/fishbigger/TapoP100/pull/21

See my comment https://github.com/fishbigger/TapoP100/commit/7d3d25ba8d12ba2816b3ee50f918c4ad1a8fb74b#r63179338

**Comment by realzoulou** [comment]
@fishbigger I think all APIs returning a non-trivial result should follow one scheme. Either all return a dict, or all return a json string. Currently getDeviceInfo() is a bit of an exception.

**Comment by fishbigger** [comment]
Both getDeviceInfo and getEnergyUsage now return a json dict ([2a15f46](https://github.com/fishbigger/TapoP100/commit/b9759f27e60a037674993705d5712a90570955090))

**Comment by fishbigger** [comment]
Uploaded to pypi in version 0.0.17.
