### ISSUE TITLE
installation 

### ISSUE THREAD

**Issue by bouba830** [fishbigger/TapoP100#48]
Hello,
first of all thank you for the work done.
here, I can't install the dependency "pip3 intall PyP100"

pi@octopi:~ $ pip3 install PyP100
-bash: pip3: command not found

I can't find anywhere the *.py files modified to enter the email and password for a P110.
Could you please help me ?
thank you

**Comment by fishbigger** [comment]
Hi,
Have you managed to install any packages through pip before? It seems you don't have `pip3` installed
