### ISSUE TITLE
Octoprint installation

### ISSUE THREAD

**Issue by atmacali** [fishbigger/TapoP100#5]
could you manage plugin for octoprint? I tried to install and had error with from PyP100 import PyP100. even i installed we need web interface or control system. could you make like tp-link plugin?

**Comment by gorobey** [comment]
@atmacali you can use this: https://github.com/kantlivelong/OctoPrint-GCodeSystemCommands for run system scripts ;)

**Comment by fishbigger** [comment]
I don't have any experience with octoprint integrations so can't make one. If you make one (or find one) using this package I'll leave a link to it somewhere but until then there isn't one :)
