### ISSUE TITLE
Fade support

### ISSUE THREAD

**Issue by mrx23dot** [fishbigger/TapoP100#53]
Which devices support fade mode?
Can it be implemented like fade_toBrightness(100)?

**Comment by fishbigger** [comment]
Hi, 
The P100 and P110 plugs definitely don't support it as they are purely binary. I assume the bulbs will support and as we don't officially support any other devices yet I think it will be safe to put the code in `PyL530.py`.
I would prefer if it was implemented in Camel Case: `fadeToBrightness(100)` so it is in standard with the other functions. 
Were you going to implement this? Or is this just a feature request.

**Comment by mrx23dot** [comment]
Just a Feature Request.
What about L510 bulb? I didn't see anything in app.

**Comment by fishbigger** [comment]
If it's not an option in the app it's unlikely that there is a way to send a fade request to the bulb. You could write your own by sending a serious of setBrightness() requests that increment/decrement towards the desired brightness but I don't think this would be suitable to be added as a function in this library.
