### ISSUE TITLE
Error with installing package PyP100 after upgrade to HA 2022.3.0b0

### ISSUE THREAD

**Issue by piio** [fishbigger/TapoP100#55]
Hi,

After upgrade HA to 2022.3.0b0 in logs I see error connected to https://github.com/pypa/pip/issues/10825 

2022-02-24 07:41:04 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package PyP100==0.0.18: warning: missing-index-doctype

× The package index page being used does not have a proper HTML doctype declaration.
╰─> Problematic URL: https://wheels.home-assistant.io/alpine-3.14/amd64/

note: This is an issue with the page at the URL mentioned above.
hint: You might need to reach out to the owner of that package index, to get this fixed. See https://github.com/pypa/pip/issues/10825 for context.
ERROR: Cannot install pyp100==0.0.18 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

From Home Assistant side there is general issue https://github.com/home-assistant/home-assistant.io/issues/21766

**Comment by piio** [comment]
After trying to manually install PyP100 it looks like problem is with pycryptodome

Building wheels for collected packages: PyP100, pycryptodome
  Building wheel for PyP100 (setup.py) ... done
  Created wheel for PyP100: filename=PyP100-0.0.18-py3-none-any.whl size=6076 sha256=e6c3e5a39638140bf34f8565638f1fac0fc18bdeb5a00c933fa827625f1b5992
  Stored in directory: /root/.cache/pip/wheels/00/92/00/64cd49f81fb6f4ec3e72644bc052ef51ca3cf3723f912c762a
  Building wheel for pycryptodome (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Testing support for clang
      Target does not support clang
      Testing support for gcc
      Target does not support gcc
      Testing support for stdint.h header
      Target does not support stdint.h header
      Testing support for 128-bit integer
      Target does not support 128-bit integer
      Testing support for cpuid.h header
      Target does not support cpuid.h header
      Testing support for intrin.h header
      Target does not support intrin.h header
      Testing support for posix_memalign
      Target does not support posix_memalign
      Testing support for memalign
      Target does not support memalign
      Testing support for SSE2(intrin.h)
      Target does not support SSE2(intrin.h)
      Testing support for SSE2(x86intrin.h)
      Target does not support SSE2(x86intrin.h)
      Testing support for SSE2(emmintrin.h)
      Target does not support SSE2(emmintrin.h)
      Warning: compiler does not support AESNI instructions
      Warning: compiler does not support CLMUL instructions
      running bdist_wheel
      running build
      running build_py
      running build_ext
      building 'Crypto.Hash._MD2' extension
      error: command 'gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycryptodome
  Running setup.py clean for pycryptodome
Successfully built PyP100
Failed to build pycryptodome
Installing collected packages: pycryptodome, idna, requests, PyP100
  Attempting uninstall: pycryptodome
    Found existing installation: pycryptodome 3.14.1
    Uninstalling pycryptodome-3.14.1:
      Successfully uninstalled pycryptodome-3.14.1
  Running setup.py install for pycryptodome ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pycryptodome did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Testing support for clang
      Target does not support clang
      Testing support for gcc
      Target does not support gcc
      Testing support for stdint.h header
      Target does not support stdint.h header
      Testing support for 128-bit integer
      Target does not support 128-bit integer
      Testing support for cpuid.h header
      Target does not support cpuid.h header
      Testing support for intrin.h header
      Target does not support intrin.h header
      Testing support for posix_memalign
      Target does not support posix_memalign
      Testing support for memalign
      Target does not support memalign
      Testing support for SSE2(intrin.h)
      Target does not support SSE2(intrin.h)
      Testing support for SSE2(x86intrin.h)
      Target does not support SSE2(x86intrin.h)
      Testing support for SSE2(emmintrin.h)
      Target does not support SSE2(emmintrin.h)
      Warning: compiler does not support AESNI instructions
      Warning: compiler does not support CLMUL instructions
      running install
      /usr/local/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running build_ext
      building 'Crypto.Hash._MD2' extension
      error: command 'gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: No metadata found in /usr/local/lib/python3.9/site-packages
  Rolling back uninstall of pycryptodome
  Moving to /usr/local/lib/python3.9/site-packages/Crypto/
   from /usr/local/lib/python3.9/site-packages/~rypto
  Moving to /usr/local/lib/python3.9/site-packages/pycryptodome-3.14.1.dist-info/
   from /usr/local/lib/python3.9/site-packages/~ycryptodome-3.14.1.dist-info
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycryptodome

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by piio** [comment]
There is already installed pycryptodome in version 3.14.1.
In home assistant wheels there is no 'pycryptodome==3.9.8' version, available are from 3.10.1 to 3.14.1

https://wheels.home-assistant.io/alpine-3.14/amd64/

Is it possible to bump required version of pycryptodome?

**Comment by piio** [comment]
I installed manually PyP100 using pip using --nodeps mode and it looks that it looks correct with pycryptodome-3.14.1

**Comment by francesco-girardi** [comment]
> Hi,
> 
> After upgrade HA to 2022.3.0b0 in logs I see error connected to [pypa/pip#10825](https://github.com/pypa/pip/issues/10825)
> 
> 2022-02-24 07:41:04 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package PyP100==0.0.18: warning: missing-index-doctype
> 
> × The package index page being used does not have a proper HTML doctype declaration. ╰─> Problematic URL: https://wheels.home-assistant.io/alpine-3.14/amd64/
> 
> note: This is an issue with the page at the URL mentioned above. hint: You might need to reach out to the owner of that package index, to get this fixed. See [pypa/pip#10825](https://github.com/pypa/pip/issues/10825) for context. ERROR: Cannot install pyp100==0.0.18 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
> 
> From Home Assistant side there is general issue [home-assistant/home-assistant.io#21766](https://github.com/home-assistant/home-assistant.io/issues/21766)

i have the same problem with my installation wichi command did you run to fix it?

**Comment by fishbigger** [comment]
Fixed in #58
