### ISSUE TITLE
Installation using pip not possible (Version 0.0.10, 2020-12-23)

### ISSUE THREAD

**Issue by SvenLudwig202** [fishbigger/TapoP100#6]
Hi,

it seems the version currently available through pip/pypi is defective. Installing it using pip install results in an error claiming that _HISTORY.md_ is missing.

`Collecting PyP100
  Using cached PyP100-0.0.10.tar.gz (4.2 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/PyP100/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-x2xw5199/pyp100_bd86ff7b0573446fb087dd6d6c10caee/setup.py'"'"'; __file__='"'"'/tmp/pip-install-x2xw5199/pyp100_bd86ff7b0573446fb087dd6d6c10caee/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-2ueeyzso
         cwd: /tmp/pip-install-x2xw5199/pyp100_bd86ff7b0573446fb087dd6d6c10caee/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-x2xw5199/pyp100_bd86ff7b0573446fb087dd6d6c10caee/setup.py", line 6, in <module>
        with open('HISTORY.md') as history_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by evlenden** [comment]
I got the same issue

**Comment by fishbigger** [comment]
Fixed in PyP100==0.0.11
