### ISSUE TITLE
pip failed to install PyP100

### ISSUE THREAD

**Issue by Adaaks** [fishbigger/TapoP100#60]
if you have this issue like i did, in this scenario i was in python version 3.9, downgrading to 3.8 fixed the job to install this module successfully.

hope this helped at least one person

**Comment by fishbigger** [comment]
Can you give a bit more detail about the issue you faced to help other people fix it like you did?

**Comment by Adaaks** [comment]
> Can you give a bit more detail about the issue you faced to help other people fix it like you did?

Essentially I was on python version 3.9, and when doing pip install PyP100 in the command bar, it failed to install the module
- I switched to version 3.8 python and it allowed me to then install the module for this.

**Comment by fishbigger** [comment]
Interesting. I believe this might have been caused with a mismatch of dependencies that had now been fixed. Thanks for reporting it anyway!
