### ISSUE TITLE
Unable to login: -1501 error code

### ISSUE THREAD

**Issue by chrischandler25** [fishbigger/TapoP100#82]
I'd love to get this to work as I'm trying to setup a halloween prop, but every time I try the login method fails with:

Exception: Error Code: -1501, Invalid Request or Credentials

My P100 is quite new, with firmware 1.2.10 which I think may be newer than most people are successfully running with.  This may be the problem.  I've tried applying the cookie parsing [PR](https://github.com/fishbigger/TapoP100/pull/77) which made no difference.

I am quite sure that my credentials are entered correctly.

Just wondering if anyone has any suggestions, or has come across this issue (perhaps with the later firmware versions).

Thanks
Chris

**Comment by fishbigger** [comment]
Hi, This should be fixed in the latest version (0.1.0) :)
