### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by gorobey** [fishbigger/TapoP100#9]
Hi!
I have issues during installation, when i run "pip3 install PyP100" i recive this respond, how can i resolve?
I have tried installation on a raspberry pi zero W, with prusaprint prepacked rasbian+octoprint OS.
![Screenshot (61)](https://user-images.githubusercontent.com/226759/107884513-bead3f80-6ef5-11eb-91fd-eaaf45ae7e7a.png)

**Comment by georgegebbett** [comment]
This doesn't look to be an issue with the repo, more an issue with pip or perhaps your internet connection
