### ISSUE TITLE
Is there a way to make the script work outside the LAN?

### ISSUE THREAD

**Issue by ginestopo** [fishbigger/TapoP100#90]
Hi,

The library works just fine for me as long as the device and the script are under the same LAN. 
Nevertheless I would like to execute the script from an external internet connection. 
It may be possible because my smartphone can handle the connection even if the devices are not under the same LAN.

Is there a way to make this work?

Thank you very much in advance. Have a nice day.

Ginés.

**Comment by fishbigger** [comment]
Hi,
At the moment it isn't possible as nobody had found the APIs that the app uses to control the plugs externally. It may be possible in future if someone discovers these APIs however.

**Comment by ginestopo** [comment]
Thanks a lot! Have a nice day 😄
